# Site settings
title: Moviex
tag_text: Moviex
description: Moviex

# Build settings
markdown: kramdown

exclude: ["README.md"]

comments :
    provider : duoshuo
    duoshuo :
          short_name : moviex
          
analytics :
    provider : custom